language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests -s konfig/tests/ --with-coverage --cover-package=konfig
after_success: coveralls